template_dir = "../../templates/substance_designer001"
title = "Substance\nDesigner"
description = "重みつきHSLフィルタ"
output_image_size = [640, 427]
output_dir = "../../out"
output_file_name = "blog20231109.png"
work_dir = "../../work"
