template_dir = "../../templates/aftereffects001"
title = "Adobe\nAfterEffects"
description = "エッセンシャルグラフィックで\nキャラクター制御"
output_image_size = [640, 427]
output_dir = "../../out"
output_file_name = "blog20231122.png"
work_dir = "../../work"
