template_dir = "../../templates/blender001"
title = "Blender"
description = "端数を許可するArrayモディファイア"
output_image_size = [640, 427]
output_dir = "../../out"
output_file_name = "blog20250104.png"
work_dir = "../../work"
