template_dir = "../../templates/blender001"
title = "Blender"
description = "BBOXに合わせてBOXを配置"
output_image_size = [640, 427]
output_dir = "../../out"
output_file_name = "blog20250124.png"
work_dir = "../../work"
