template_dir = "../../templates/substance_painter001"
title = "Substance\nPainter"
description = "SDFテクスチャフィルター"
output_image_size = [640, 427]
output_dir = "../../out"
output_file_name = "blog20231008.png"
work_dir = "../../work"
